"use client";
import MessageCard from "@/components/MessageCard";

const Dashboard = () => {
  const message = {
    _id: "sdfew",
    content:
      "Generated by create next app Generated by create next app Generated by create next app Generated by create next app",
    createAt: new Date(),
  };
  const onMessageDelete = () => {
    return;
  };
  return (
    <div>
      <MessageCard
        message={message}
        onMessageDelete={onMessageDelete}
      />
    </div>
  );
};
export default Dashboard;
