import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SessionProviderContext from "./context/SessionProvider";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/toaster";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <SessionProviderContext>
        {/* //TODO add darkmode in app */}
        <body className={(cn(inter.className), "")}>
          {children}
          <Toaster />
        </body>
      </SessionProviderContext>
    </html>
  );
}
//TODO: make all dark and light mode colors accurate
